jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |-
            *
            !.git/*
  units1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "Hello World" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - init
  units2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dave"
        name: Run units2
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units1
  units3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: cat hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units2
  printer-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dev"
      - run: echo ${{ vars.test }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units3
    environment: dev
  printer-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "prod"
      - run: echo ${{ vars.test }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - printer-0
    environment: prod
name: main
on:
  - push
