jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |-
            *
            !.git/*
  units1-ae1e6703:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "Hello World" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - init
  units2-cfba737e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dave"
        name: Run units2
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units1-ae1e6703
  units3-6b643fbc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: cat hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units2-cfba737e
  printer-f0e11e04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dev"
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units3-6b643fbc
    environment: dev
  printer-504d744d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "prod"
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - printer-f0e11e04
    environment: prod
name: main
on:
  - push
