jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |-
            *
            !.git/*
  units1-e4e57cf7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "Hello World" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - init
  units2-e8b4936a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dave"
        name: Run units2
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units1-e4e57cf7
  units3-b40512e7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: cat hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units2-e8b4936a
  printer-d64d224c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "dev"
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - units3-b40512e7
  printer-7dd0b01d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: echo "prod"
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "*"
    needs:
      - printer-d64d224c
name: main
on:
  - push
